[build-system]
requires = ["setuptools>=64", "wheel", "pybind11>=2.13", "numpy>=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tmm_faster"
version = "0.1.1"
description = "A lightweight Python library with a C++ core for very fast calculations of reflection and transmission spectra in optical thin-film systems using the transfer-matrix method."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.0",
]

[tool.setuptools.packages.find]
include = ["tmm_faster*"]
exclude = ["examples*", "tests*"]
